general.import = [ "~/.config/alacritty/simple-dark.toml" ]

#[colors.primary]
#background = "#000000"

[env]
TERM = "xterm-256color"

[font]
size = 8.0

#[font.bold]
#family = "JetBrainsMono Nerd Font Mono"
#style = "Bold"
#
#[font.bold_italic]
#family = "JetBrainsMono Nerd Font Mono"
#style = "Bold Italic"
#
#[font.italic]
#family = "JetBrainsMono Nerd Font Mono"
#style = "Italic"

[font.normal]
#family = "JetBrainsMono Nerd Font Mono"
family = "Roboto Mono"
style = "Medium"
