#import = [ "~/.config/alacritty/catppuccin-mocha.toml" ]

#[colors.primary]
#background = "#000000"

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.normal]
family = "JetBrains Mono"
style = "Bold"

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"
