require("core.options")
require("core.remap")
require("core.lsp")
require("core.packmanager")
require("core.plugins.lualine")
require("core.plugins.catppuccin")
require("core.plugins.dashboard")
require("core.plugins.mason")
require("core.plugins.mason-lsp")
require("core.plugins.mini-icons")
require("core.plugins.mini-pick")
require("core.plugins.nvim-autopairs")
require("core.plugins.nvim-web-devicons")
require("core.plugins.orgmode")
require("core.plugins.telescope")
require("core.plugins.treesitter")

vim.cmd.colorscheme("catppuccin")
